### ISSUE TITLE
Adding a Cookie condition for redirects

### ISSUE THREAD

**Issue by sirrocco** [netlify/gatsby-plugin-netlify#72]
Hi, 

I'm trying to add a cookie condition to a redirect rule - something like: 
```typescript
// don't redirect if the user selected a preferred language
createRedirect({
      fromPath: '/*',
      toPath: '/*',
      statusCode: 200,
      Cookie: 'user_preferred_language'
})
```
however, the outputted `_redirects` file is ignoring the `Cookie` value due to
```typescript
 const NETLIFY_REDIRECT_KEYWORDS_ALLOWLIST = new Set([
    `query`,
    `conditions`,
    `headers`,
    `signed`,
    `edge_handler`,
    `Language`,
    `Country`,
  ])
```
This should be supported as per documentation: https://docs.netlify.com/routing/redirects/redirect-options/#redirect-by-cookie-presence

Can this be updated or am I misunderstanding something?

Thank you

**Comment by sarahetter** [comment]
Hey! This is happening because [gatsby's `createRedirect`](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createRedirect) does not take the Cookie property. We don't extend the `createRedirect` from gatsby itself, but allow users to add Cookie redirects within Netlify by adding it to a `_redirects` file, or a `netlify.toml` file.

Closing as this is working as expected.
