### ISSUE TITLE
Query formatting is incorrect

### ISSUE THREAD

**Issue by void--** [netlify/gatsby-plugin-netlify#79]
Currently the plugin assumes that any additional config keywords should be appended to the redirect entry in a `${key}=${value}` format -- this works for Language and Country and maybe others, but query params need to be parsed and added inline between the source and destination, e.g:

`/source queryParamOne=value1 queryParamTwo=value2 /destination 301`

**Comment by fool** [comment]
cf https://netlify.zendesk.com/agent/tickets/83410 is an internal link for the netlify team to some more context shared with us in the helpdesk

**Comment by ascorbic** [comment]
Hi. Can you explain a bit more what you're trying to do? Are these redirects being created in Gatsby, or are these `_redirects` that you are creating yourself? If it's the former, can you give a bit more detail on how you are creating them.

**Comment by void--** [comment]
Hey Matt! For sure -- these are redirects using the `createRedirect` action. We're creating these redirects from a content type in contentful that's maintained by our production team, and they're requesting the ability to redirect using paths with specific query parameters, e.g. `/test?blah=foo` would redirect, while `/test` would not. Currently there's no code that dictates what the structure should be... I suppose something like the following might be reasonable?

```
createRedirect({
    fromPath: node.from,
    toPath: node.to,
    statusCode: node.statusCode,
    force: node.force,
    query: { blah: "foo", bar: "baz"}
});
```

**Comment by ascorbic** [comment]
Hi @void-- 
Sorry for the delay in getting back to you in this. It's a slightly complicated one, as this is a feature that's not supported in Gatsby itself. In general we'd not try to add extra features to a framework via the plugin, because it gets hard to maintain and confusing to support. That said, as you point out the plugin already does that with Country and Language, so it's less clean cut and we could consider it, especially as you are an enterprise customer. I will allow the support team to follow up directly and handle the details of escalating a feature request on your behalf.

**Comment by void--** [comment]
No worries! I think this feature is supported in gatsby -- it seems like they assume that the `fromPath` can have query parameters included, which is how they handle it in gatsby cloud (see "Query param redirects" here: https://support.gatsbyjs.com/hc/en-us/articles/1500003051241-Working-with-Redirects).

In fact, it would probably be better to follow this pattern rather than my suggestion above.

Thanks for your help!

**Comment by ascorbic** [comment]
I just spotted that! It looks like this was added last week. We will aim to add support for that and for the new syntax for country and language. I've opened a new issue (#93) all of those, and close this in favour of it.
